name: "e2e: noscience, gha"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/e2e-common.yml
    with:
      suffix: "noscience"
      ci_repo: ""
      runner: "['ubuntu-latest']"
      kind_version: "v0.20.0"
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}